#!/bin/bash

echo "🚀 デプロイメントチェックリスト"
echo "================================"
echo ""
echo "1. Vercelダッシュボードでデプロイ状況を確認："
echo "   https://vercel.com/dashboard"
echo ""
echo "2. 環境変数が設定されているか確認："
echo "   - VITE_SUPABASE_URL"
echo "   - VITE_SUPABASE_ANON_KEY"
echo "   - VITE_API_URL"
echo "   - SUPABASE_SERVICE_ROLE_KEY"
echo "   - RAKUTEN_APP_ID"
echo "   - SENDGRID_API_KEY"
echo ""
echo "3. デプロイ完了後、以下の機能をテスト："
echo "   ✓ ホームページの表示"
echo "   ✓ ホテル検索機能"
echo "   ✓ リアルタイム検索"
echo "   ✓ 通知機能"
echo "   ✓ ユーザー登録/ログイン"
echo ""
echo "4. エラーログの確認："
echo "   Vercel Functions タブでAPIログを確認"
echo ""
echo "5. 本番URL："
echo "   https://hotelbookingsystem-seven.vercel.app"
echo ""
echo "問題がある場合は、VERCEL_ENV_VARS.md を参照してください。"