name: Deploy to Vercel

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main ]

# env section removed - Vercel CLI will use .vercel/project.json

jobs:
  deploy-preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      # Skip pull step - use direct deployment
        
      # Skip build step - using static deployment
        
      - name: Deploy to Vercel Preview
        run: |
          export VERCEL_ORG_ID="team_CxYuNDI2LPUdzABJOsjF35QQ"
          export VERCEL_PROJECT_ID="prj_p0dOI7mwc1jq4uPcvqnBbgok4vLt"
          vercel deploy --yes --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt
          echo "PREVIEW_URL=$(cat deployment-url.txt)" >> $GITHUB_OUTPUT
        id: deploy
        
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployment ready!\n\nURL: ${{ steps.deploy.outputs.PREVIEW_URL }}'
            })

  deploy-production:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      # Skip pull step - use direct deployment
        
      # Skip build step - using static deployment
        
      - name: Deploy to Vercel Production
        run: |
          export VERCEL_ORG_ID="team_CxYuNDI2LPUdzABJOsjF35QQ"
          export VERCEL_PROJECT_ID="prj_p0dOI7mwc1jq4uPcvqnBbgok4vLt"
          vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }}